extend type Query {
    entities: EntityResponseArray
    entityById(_id: ID!): EntityResponse
    entityByLabel(label: String!): EntityResponse
}

extend type Mutation {
    entityCreateOne(entity: EntityMutationInput!): EntityResponse
    entityUpdateOne(_id: ID!, entity: EntityMutationInput!): EntityResponse
    entityRemoveOne(_id: ID!): EntityResponse

    entityUpdateOneColor(_id: ID!, color: EntityMutationColor): EntityResponse
    entityRemoveOneColor(_id: ID!): EntityResponse

    entityCreateMany(entities: [EntityMutationInput]!): EntityResponseArray
    entityUpdateMany(entities: [EntityMutationInputWithId]!): EntityResponseArray
    entityRemoveMany(ids: [ID]!): EntityResponseArray
}