export const
TOGGLE_REFETCH = "TOGGLE_REFETCH",
SET_LEXICONS_DATA = "SET_LEXICONS_DATA",
SET_ENTITIES_DATA = "SET_ENTITIES_DATA",
SET_LEXICONS_SEARCH = "SET_LEXICONS_SEARCH",
TOGGLE_MODEL_CONFIRM = "TOGGLE_MODEL_CONFIRM",
TOGGLE_OPTIONS_EXACT_MATCH = "TOGGLE_OPTIONS_EXACT_MATCH";