export const
TOGGLE_MODEL_ENTITY = "TOGGLE_MODEL_ENTITY",
SET_ENTITY_MODAL_DATA = "SET_ENTITY_MODAL_DATA",
TOGGLE_ENTITY_MODAL_REFETCH = "TOGGLE_ENTITY_MODAL_REFETCH",
SET_ENTITY_MODAL_INPUT = "SET_ENTITY_MODAL_INPUT";